version: 0.0
os: ubuntu

hooks:
  ApplicationInstall:
    - location: scripts/before_server
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/start_server
      timeout: 300
      runas: root
 
 